django_container/django_container/common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

django_container/django_container/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('dust_checker', include('dust_checker.urls')),
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_container/django_container/dust_checker/urls.py
from django.urls import path
from . import views

app_name = 'dust_checker'

urlpatterns = [
    path('', views.index, name='index'),
    path('/detail', views.detail, name='detail'),
]

django_container/django_container/common/models.py
from django.db import models

# Create your models here.

django_container/django_container/dust_checker/models.py
from django.db import models

# Create your models here.

django_container/django_container/common/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'main.html')

django_container/django_container/dust_checker/views.py
from django.shortcuts import render
from .api import check_air

def index(request):
    res = check_air()
    pm10 = res.get('가양동')
    context = {'station': '강서구', 'pm10': pm10}
    return render(request, 'dust_checker/dust_main.html', context)

def detail(request):
    res = check_air()
    context = {'dust': res}
    return render(request, 'dust_checker/dust_detail.html', context)

django_container/django_container/templates/dust_checker/dust_detail.html
{% extends 'main.html' %}
{% block content %}
<!-- ---------------------- [edit] ------------------------ -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<div class="row justify-content-center mb-2">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    {% for key in dust.keys %}
                        <th scope="col">{{key}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for value in dust.values %}
                        <td>{{value}}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex justify-content-center mb-2">
    <div class="col-md-6">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script>
var label = new Array();
var data = new Array();
{% for key, value in dust.items %}
    label.push('{{key}}');
    data.push('{{value}}');
{% endfor %}


var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: label,
        datasets: [{
            label: '미세먼지 수치',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: data
        }]
    },

    // Configuration options go here
    options: {}
});
</script>
<!-- -------------------------------------------------------- -->
{% endblock %}

django_container/django_container/templates/dust_checker/dust_main.html
{% extends 'main.html' %}
{% block content %}
<div class="row justify-content-center mb-2">
    <div class="col-md-4">
        <div class="card" >
            <img src="/static/images/dust.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">미세먼지 수치</h5>
                <p class="card-text">{{pm10}}</p>
                <a href="{% url 'dust_checker:detail'%}" class="btn btn-primary">>> 자세히</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_container/django_container/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">COLOK-COLOK</a>    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dust_checker:index' %}">미세먼지 확인</a>        </li>
       
      
    </div>
  </div>
</nav>

django_container/django_container/templates/index.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Cover</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Contact</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>


    
  </body>
</html>

django_container/django_container/templates/main.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Main Page</title>
</head>
<body>
{% include "header.html" %}
<!-- <img src="/static/images/dustmain.jpg" class="card-img-top" alt="..."> -->
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="/static/images/dust.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/static/images/dustmain.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/static/images/dust.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
</div>

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</body>
</html>

django_container/django_container/templates/main_copy0.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Main Page</title>
</head>
<body>
{% include "header.html" %}
MAIN PAGE. 추후 추가할 예정임.
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</body>
</html>